/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 main.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/main.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Wolf3D_Hair.geometry} material={materials['Wolf3D_Hair.001']} />
      <mesh geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.001']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.001']} />
      <mesh geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.001']} />
      <mesh geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.001']} />
      <mesh geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.001']} />
      <mesh geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.001']} />
    </group>
  )
}

useGLTF.preload('/main.glb')
